### ISSUE TITLE
ICU DLLs no longer have versioned filenames.

### ISSUE THREAD

**Issue by rkirsling** [WebKitForWindows/WinCairoRequirements#19]
As of #18, the ICU DLL filenames have changed (e.g. `icudt61.dll` → `icudt.dll`) such that putting WinCairoRequirements on one's PATH fails to prioritize these DLLs over the ones in system32.

This is inconvenient for folks who are interested in using the JSC shell on 64-bit Windows: 
https://github.com/GoogleChromeLabs/jsvu/issues/53

(Belatedly creating an issue here for @donny-dont's tracking purposes. :smile:)

**Comment by donny-dont** [comment]
Fixed in d96d7e47cf339b2bbc2d26db335d9b86b4ed1bf7
